import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Deployment path
const vaultPath = "/Users/boss/Library/Mobile Documents/iCloud~md~obsidian/Documents/Life_OS/.obsidian/plugins/obsidian_ai_copilot";

// Always delete main.js first to force a full fresh build (bypass incremental caching)
if (fs.existsSync("main.js")) {
	fs.unlinkSync("main.js");
	console.log("Deleted old main.js — forcing fresh build...");
}

const buildOptions = {
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian", "electron",
		"@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
		"@codemirror/language", "@codemirror/lint", "@codemirror/search",
		"@codemirror/state", "@codemirror/view",
		"@lezer/common", "@lezer/highlight", "@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
	],
};

if (prod) {
	// Full fresh build — no context, no incremental cache
	const result = await esbuild.build(buildOptions);
	if (result.errors && result.errors.length > 0) {
		console.error("Build failed!");
		process.exit(1);
	}
	console.log("Build complete. Deploying to vault...");

	// Deploy to vault
	try {
		if (!fs.existsSync(vaultPath)) {
			fs.mkdirSync(vaultPath, { recursive: true });
		}
		for (const file of ['main.js', 'manifest.json', 'styles.css']) {
			if (fs.existsSync(file)) {
				const dest = path.join(vaultPath, file);
				try { fs.unlinkSync(dest); } catch(e) {}
				fs.copyFileSync(file, dest);
				console.log(`  Deployed ${file} → vault`);
			}
		}
		console.log(`Successfully deployed to ${vaultPath}`);
	} catch (err) {
		console.error(`Failed to deploy: ${err.message}`);
	}
	process.exit(0);
} else {
	// Watch mode — use context for incremental builds
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
